CREATE TABLE dts_specimen_inventory_v1_0 (
  id int(11) NOT NULL AUTO_INCREMENT,
  study_protocol_id varchar(50) DEFAULT NULL,
  study_protocol_version varchar (255) DEFAULT NULL,
  site_number varchar(50) DEFAULT NULL,
  collection_site_country varchar (255) DEFAULT NULL,
  date_departed_site datetime DEFAULT NULL,
  subject_num varchar(50) DEFAULT NULL,
  subject_gender varchar(50) DEFAULT NULL,
  subject_date_of_birth date DEFAULT NULL,
  subject_race varchar (50) DEFAULT NULL,
  subject_ethnicity varchar (50) DEFAULT NULL,
  subject_enrollment_status varchar (50) DEFAULT NULL,
  specimen_collect_date date DEFAULT NULL,
  specimen_collect_time time DEFAULT NULL,
  received_datetime datetime DEFAULT NULL,
  treatment varchar(50) DEFAULT NULL,
  arm varchar(50) DEFAULT NULL,
  visit_name varchar(50) DEFAULT NULL,
  visit_date date DEFAULT NULL,
  visit_day varchar (50) DEFAULT NULL,
  visit_week varchar (50) DEFAULT NULL,
  visit_timepoint varchar (50) DEFAULT NULL,
  specimen_barcode varchar(50) DEFAULT NULL,
  specimen_identifier varchar(50) DEFAULT NULL,
  specimen_type varchar(50) DEFAULT NULL,
  specimen_name varchar(50) DEFAULT NULL,
  specimen_volume varchar(50) DEFAULT NULL,
  specimen_volume_units varchar(50) DEFAULT NULL,
  specimen_mass varchar(50) DEFAULT NULL,
  specimen_mass_units varchar(50) DEFAULT NULL,
  specimen_designation varchar(50) DEFAULT NULL,
  specimen_designation_detail varchar(50) DEFAULT NULL,
  specimen_collection_tube_type varchar (50) DEFAULT NULL,
  specimen_quality varchar (50) DEFAULT NULL,
  specimen_parent_id varchar(50) DEFAULT NULL,
  specimen_ischild varchar(50) DEFAULT NULL,
  specimen_child_type varchar(50) DEFAULT NULL,
  specimen_condition varchar(50) DEFAULT NULL,
  specimen_status varchar(50) DEFAULT NULL,
  specimen_comment varchar(255) DEFAULT NULL,
  shipped_date datetime DEFAULT NULL,
  shipped_location varchar(50) DEFAULT NULL,
  storage_vendor varchar(50) DEFAULT NULL,
  storage_facility_name varchar(50) DEFAULT NULL,
  storage_location varchar(50) DEFAULT NULL,
  testing_description varchar(255) DEFAULT NULL,
  vendor_code varchar(255) NOT NULL,
  record_status varchar(50) NOT NULL DEFAULT 'new',
  record_created timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX IDX_dts_specimen_inventory_v1_0_site_number (site_number),
  INDEX IDX_dts_specimen_inventory_v1_0_specimen_barcode (specimen_barcode),
  INDEX IDX_dts_specimen_inventory_v1_0_specimen_parent_id (specimen_parent_id),
  INDEX IDX_dts_specimen_inventory_v1_0_study_protocol_id (study_protocol_id),
  INDEX IDX_dts_specimen_inventory_v1_0_subject_num (subject_num)
)
ENGINE = INNODB
AUTO_INCREMENT = 111963
AVG_ROW_LENGTH = 281
CHARACTER SET utf8
COLLATE utf8_unicode_ci;